name: Deploy To Prod Server

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.18.1"

      - name: Deploy to Prod Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.SERVER_HOST}}
          key: ${{secrets.SERVER_SSH_KEY}}
          username: ${{secrets.SERVER_USERNAME}}
          script: |
            cd kelvinboj-frontend
            git stash
            git pull https://x-access-token:${{secrets.GITHUB_TOKEN}}@github.com/AJIS-GROUP/KelvinBoj main
            npm install
            export NODE_OPTIONS="--max-old-space-size=4096"
            npm run build
            npm run start:prod
            echo "Deployment to Prod Server Completed"
